sprint1
ClevertecFrontendLab/sprint1-AdrianDmitruk pull request #1
Opened 2023-01-29 20:01 UTC by AdrianDmitruk

2023-01-29 20:04 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675022649/content-window.png)

2023-01-29 20:08 UTC, SergeyGlazun requested changes
![image](https://user-images.githubusercontent.com/70904466/215353045-eeca43a9-0988-444f-b860-cceb856f3057.png)
проверти адапти или размеры карточки, также задний фон header должен быть на весь экран, свертись с макетом

2023-01-29 20:18 UTC, AdrianDmitruk commented
Это мои скрины?

2023-01-29 20:24 UTC, AdrianDmitruk commented
У меня же вист скрины без этих отступов и в браузере все ок

2023-01-29 21:06 UTC, SergeyGlazun commented
![image](https://user-images.githubusercontent.com/70904466/215355549-7c7a4eca-b3ca-45d4-949e-9ac4dbcecc46.png)
отступы еще ладно возможно бот так сфоткал, дальше вроде ном header, вся суть что бот фоткает пол карточки а это значит проблема с адаптивном или размерами или не правильным расположением

2023-01-30 15:41 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1675093293/content-window.png)

2023-01-30 15:50 UTC, SergeyGlazun approved these changes

2023-01-30 15:51 UTC, merged